---   
# connect to Jenkins
  - name: login Jenkins
    shell: java -jar "/opt/jenkins-cli.jar" -s http://localhost:8080/ -user admin

# copy pipeline config
  - name: copy templates/config.xml
    copy:
      src: templates/config.xml
      dest: ./

# copy Jenkinsfile
  - name: copy Jenkinsfile
    copy:
      src: ../Jenkinsfile
      dest: ./

# install plugins
  - name: Download Jenkins plugins
    shell: java -jar "/opt/jenkins-cli.jar" -s http://localhost:8080/ -auth admin:admin install-plugin {{item}}
    with_items:
      - workflow-cps
      - workflow-aggregator
      - pipeline-maven
      - build-pipeline-plugin
      - git

#restart jenkins
  - name: Restart Jenkins
    service: name=jenkins state=restarted

  - name: Wait for Jenkins to restart
    wait_for:
      host=localhost
      port=8080
      delay=20
      timeout=300

# login
  - name: login Jenkins
    shell: java -jar "/opt/jenkins-cli.jar" -s http://localhost:8080/ -user admin

# create job
  - name: create Jenkins job from configuration file
    shell: java -jar "/opt/jenkins-cli.jar" -s http://localhost:8080 -auth admin:admin create-job projet-CI-CD <./config.xml

# # config Maven Home
#   - name: Config Maven home /opt/apache-maven-3.6.1
#     shell: ...

# # config Java home
#   - name: config java home
#     shell: ...

# execute the job
  - name: execute the job
    shell: java -jar "/opt/jenkins-cli.jar" -s http://localhost:8080 -auth admin:admin build projet-CI-CD
