---
- hosts: jenkins 
  become: true 
  roles: 
    - geerlingguy.git
    - geerlingguy.java
    - tecris.maven
    - geerlingguy.jenkins
    - jenkinsconfig
# ajouter role install plugin (build-pipeline, maven-integration, ...) + build pipeline

